version: "3"
services:
  app:
    restart: always
    build:
      context: ./
      args:
        HOST_UID: $HOST_UID
        HOST_GID: $HOST_GID
        MY_USER: $MY_USER
        MY_GROUP: $MY_USER
        TZ: $TZ
    volumes:
      - type: bind
        source: ./
        target: /home/$MY_USER/app
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]
